### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by jonchan51** [rc-dining-bot/telegram-bot#6]

**Comment by dtjldamien** [comment]
import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
at the beginning of your script.

You can also use logs in your application by calling logging.getLogger() and setting the log level you want:

logger = logging.getLogger()
logger.setLevel(logging.INFO)
If you want DEBUG logs instead:

logger.setLevel(logging.DEBUG)
